spring:
  datasource:
    url: jdbc:h2:mem:issueDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  application:
    name: issue-service
server:
  port: 8887
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka