spring:
  datasource:
    url: jdbc:h2:mem:readerdb
    username: sa
    password:

  application:
    name: reader-service

server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
