spring:
  datasource:
    url: jdbc:h2:mem:bookDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  application:
    name: book-service
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

